### ISSUE TITLE
Add SRP compliance: report provenance file

### ISSUE THREAD

**Issue by antgamdia** [vmware-tanzu/kubeapps#5176]
**Summary**
As part of the requirements in VMware for GA products, we need to comply with the SRP process. Specifically, we need to produce and report a `source provenance` file of our product.

**Background and rationale**
This is a mandatory step.

**Description**
On each build we have to create and report a `source-provenance.json` file. This file is generated by a binary provided by VMware.

**Acceptance criteria**
  - There is a CI step reporting the `source-provenance.json` file to the proper location on each build.

**Additional context**
N/A

**Comment by antgamdia** [comment]
For now, we have successfully reported the provenance of the previous v2.4.6 version:

```
{"id": "http://vmware.com/schemas/software_provenance-0.2.5.json", "root": "uid.obj.build.circleci(instance='circleci.com',type='github',namespace='vmware-tanzu/kubeapps',branch='main',commit_id='11c87926d6cd798af72875d01437d15ae8d85b9a',build_id='7653/2bb4c509-3597-4673-b819-d6d1be9abc52/87960')", "tools": {"https://artifactory.eng.vmware.com/artifactory/helix-docker-local/cli/srpcli/0.2.20220809201724-53aa841-38/linux/srp": null}, "all_components": {"uid.obj.build.circleci(instance='circleci.com',type='github',namespace='vmware-tanzu/kubeapps',branch='main',commit_id='11c87926d6cd798af72875d01437d15ae8d85b9a',build_id='7653/2bb4c509-3597-4673-b819-d6d1be9abc52/87960')": {"name": "kubeapps", "version": "v2.4.6", "typename": "uid.obj.build.circleci", "buildtype": "release", "components": [], "build_number": "2bb4c509-3597-4673-b819-d6d1be9abc52", "all_ephemeral": true, "source_repositories": [{"ref": "11c87926d6cd798af72875d01437d15ae8d85b9a", "host": "github.com", "repo": "vmware-tanzu/kubeapps.git", "paths": ["/"], "branch": "main", "content": "source", "protocol": "https"}, {"ref": "9c63990c847dce9e6dca44ad39f7cc4e547bd55f", "host": "github.com", "repo": "kubernetes/code-generator", "paths": ["/cmd/apprepository-controller/vendor/k8s.io/code-generator"], "branch": "HEAD", "content": "source", "protocol": "https"}]}}}
````

The CI work is almost done at #5177, but the updated upstream `srp` binary is not published yet. Once it is, we will be able to start reporting on each build.

**Comment by antgamdia** [comment]
For the record, the network provenance report fails as of today. I've pushed the commented-out code as we might need it in the upcoming months.

```console
INFO 2022-08-10 13:07:56,769 Observer:__init__ 133:  Platform: linux, Root dir: /home/circleci/project/bin, Logging dir: /home/circleci/project/bin/runtime/logs, Working dir: /home/circleci/project/bin/runtime/observer, Home dir: /home/circleci, Disable config: False, Append mode: False, tcpdump: True, Observer host: 127.0.0.1, Observer port: 8989, Differentiate method : False, Output directory: ./provenance-go, Command: [go mod download -x]
INFO 2022-08-10 13:07:56,769 Observer:run 32: Start observer server ...
INFO 2022-08-10 13:07:56,769 Observer:run 35: Setting mitmdump access_log path: /home/circleci/project/bin/runtime/logs/access.log
INFO 2022-08-10 13:07:56,769 Observer:run 40: Setting mitmdump error log path: /home/circleci/project/bin/runtime/logs/mitmdump_error.log
INFO 2022-08-10 13:07:56,770 Observer:is_port_in_use 39: 127.0.0.1:8989 in use: False
INFO 2022-08-10 13:07:56,771 Observer:run_cmd 72: Command: [/home/circleci/project/bin/python3 /home/circleci/project/bin/mitmdump -v -p 8989] with no wait....
INFO 2022-08-10 13:07:56,771 Observer:run 79: tcpdump mode is Enabled/On.Starting httpry ...
INFO 2022-08-10 13:07:56,781 Observer:run_cmd 94: Command: [/usr/bin/sudo ls /], return code: 0, outputs: None, errors: None
INFO 2022-08-10 13:07:56,787 Observer:run_cmd 94: Command: [/usr/bin/sudo rm -f /home/circleci/project/bin/runtime/logs/httpry_access.log], return code: 0, outputs: , errors: None
Traceback (most recent call last):
  File "/home/circleci/project/bin/observer_agent.py", line 281, in <module>
    run(config)
  File "/home/circleci/project/bin/observer_agent.py", line 134, in run
    stderr=subprocess.DEVNULL,
  File "/home/circleci/project/bin/helper.py", line 89, in run_cmd
    f"Command: [{cmd}] failed, return code: {proc.poll()}, outputs: {outs}, errors: {errs}"  # noqa
Exception: Command: [/usr/bin/sudo /home/circleci/project/bin/httpry  -d -o /home/circleci/project/bin/runtime/logs/httpry_access.log  -P /home/circleci/project/bin/runtime/logs/httpry.pid] failed, return code: 2, outputs: None, errors: None

Exited with code exit status 1
CircleCI received exit code 1
````

**Comment by antgamdia** [comment]
Confirming that we are successfully pushing SRP data on each build (aka push to `main` OR new release):

![image](https://user-images.githubusercontent.com/11535726/186398688-48582f95-5500-4306-a416-304f120428df.png)
